### ISSUE TITLE
AWS Cognito Web Set Keys

### ISSUE THREAD

**Issue by ImJacobChen** [reapit/foundations-documentation#84]
Summary:

We require the correct `https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json` URL to download the keys to validate the tokens but it is not supplied in the documentation.

Can this be added? It is not found anywhere on the following page.

https://foundations-documentation.reapit.cloud/api/reapit-connect

Thanks,

Jacob

**Comment by HollyJoyPhillips** [comment]
Added ticket to main repo https://github.com/reapit/foundations/issues/4507
